import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import ReactQueryProvider from "@/lib/reactQueryProvider";
import Main from "./main";
import ThemeInitializer from "@/utilities/themeInitializer";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Import theme overrides 
// TODO move to other file when it's bigger
// import "@/styles/default.css";
// import "@/styles/brann.css";
// import "@/styles/vif.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Get target theme from environment variable
  // TODO move to other file when it's bigger
  // const theme = process.env.NEXT_PUBLIC_TARGET || 'default';
  
  return (
    <html lang="en">
      <body>
        <ThemeInitializer />
        <ReactQueryProvider>
          <Main>
            {children}
          </Main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
